### PR TITLE
Spec draft

### PR DESCRIPTION
**Pull request by jeremyroman**
This is a first pass at formalizing the portals work into a specification. There's still some stuff left out here to avoid making this PR any bigger. It's largely noted either in inline issues in the spec or existing GitHub issues.

Preview: https://rawgit.com/jeremyroman/portals/spec-draft/index.html

### CODE REVIEW

**Comment by jeremyroman** [comment]
@lucasgadani I can't seem to assign you as a reviewer, but I'd also like you to look at this.

I'm sure we'll have to get Domenic (or someone else) to take a proper look at this, but since we're still early days it's probably fine to stage this in the GitHub repo and do a review from there. WDYT?

**Comment by lucasgadani** [comment]
Thanks for working on this! The draft so far LGTM.

I think we should expand a bit on the lifetime of the PortalHost object, and when it has an associated browsing context. In particular, since we are dealing with two independent event loops, the portal browsing context's event loop needs to be notified that it's PortalHost object is no longer associated host (i.e. this isn't a synchronous operation as it might be implied in the "activate a portal browsing context" in section 2).

**Comment by KenjiBaheux** [comment]
@lucasgadani I've added you to the contributors, check your inbox for an invite link.

**Comment by jeremyroman** [comment]
PTAL.

**Comment by lucasgadani** [comment]
Thanks, the draft LGTM.

I think we'll also need to think about and include the fallback behavior of <portal>. In particular, what will happen with children of the <portal> element, but it should be ok merging this and working on this as a follow-up.

**Comment by jeremyroman** [comment]
Yes, I don't mean to imply that there are no remaining things to describe. :smile:

**Pull request merged**
